CREATE TABLE tb_fornecedor(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
cnpj VARCHAR(12) NOT NULL,
nome VARCHAR(255) NOT NULL,
telefone VARCHAR(20) NOT NULL,
email VARCHAR(255) NOT NULL,
logradouro VARCHAR(255) NOT NULL,
numero VARCHAR(255) NOT NULL,
cep VARCHAR(8) NOT NULL,
complemento VARCHAR(255)
);